namespace Dotnet.WorkspaceExplorer.WorkspaceIndex

open System
open System.Collections.Generic
open System.IO
open Dotnet.WorkspaceExplorer.ProjectEvaluation
open Dotnet.WorkspaceExplorer.Solutions
open Dotnet.WorkspaceExplorer.Workspaces

type private SemanticFile =
    { ItemType: string
      RelativePath: string
      CanonicalRelativePath: string
      Ordinal: int
      DimensionOrder: int }

type private SemanticFolder =
    { RelativePath: string
      Ordinal: int
      DimensionOrder: int }

type private DependencyCandidate =
    { Identity: string
      Name: string
      CategoryOrder: int
      Details: DependencyDetail array }

module internal SemanticProjectProjection =
    let private fileItemTypes =
        HashSet<string>(
            [ "Compile"; "Content"; "None"; "EmbeddedResource" ],
            StringComparer.Ordinal
        )

    let private pathComparer insensitive =
        if insensitive then
            StringComparer.OrdinalIgnoreCase
        else
            StringComparer.Ordinal

    let private canonical insensitive (value: string) =
        if insensitive then value.ToUpperInvariant() else value

    let private canonicalPath insensitive (value: string) =
        value.Replace('\\', '/') |> canonical insensitive

    let private isSameOrDescendant root candidate =
        let relative = Path.GetRelativePath(root, candidate)

        relative = "."
        || (not (Path.IsPathRooted relative)
            && relative <> ".."
            && not (
                relative.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
            )
            && not (
                relative.StartsWith($"..{Path.AltDirectorySeparatorChar}", StringComparison.Ordinal)
            ))

    let private propertyDirectories
        (projectDirectory: string)
        (names: string list)
        fallback
        (snapshot: ProjectEvaluationSnapshot)
        =
        let values =
            snapshot.Dimensions
            |> Seq.collect _.Properties
            |> Seq.filter (fun property ->
                names
                |> List.exists (fun name ->
                    String.Equals(property.Name, name, StringComparison.Ordinal)))
            |> Seq.choose (fun property ->
                if
                    String.IsNullOrWhiteSpace property.Value
                    || property.Value.Contains("$(", StringComparison.Ordinal)
                then
                    None
                else
                    try
                        Some(Path.GetFullPath(property.Value, projectDirectory))
                    with
                    | :? ArgumentException
                    | :? NotSupportedException
                    | :? PathTooLongException -> None)
            |> Seq.distinct
            |> Seq.toArray

        if values.Length = 0 then
            [| Path.GetFullPath(fallback, projectDirectory) |]
        else
            values

    let private isGenerated projectDirectory snapshot path =
        let intermediate =
            propertyDirectories
                projectDirectory
                [ "BaseIntermediateOutputPath"; "IntermediateOutputPath" ]
                "obj"
                snapshot

        let output =
            propertyDirectories projectDirectory [ "BaseOutputPath"; "OutputPath" ] "bin" snapshot

        Seq.append intermediate output
        |> Seq.exists (fun root -> isSameOrDescendant root path)

    let private isAutoGenerated (item: EvaluatedItem) =
        item.Metadata
        |> Seq.exists (fun metadata ->
            String.Equals(metadata.Name, "AutoGen", StringComparison.OrdinalIgnoreCase)
            && String.Equals(metadata.Value, "true", StringComparison.OrdinalIgnoreCase))

    let private frameworkOrder (dimension: ProjectEvaluationDimension) =
        if dimension.IsOuterBuild then
            struct (0, String.Empty)
        else
            struct (1, dimension.TargetFramework.Value.Value)

    let private semanticFiles insensitive (snapshot: ProjectEvaluationSnapshot) =
        let projectDirectory =
            Path.GetDirectoryName(snapshot.ProjectPath.Value) |> Option.ofObj

        match projectDirectory with
        | None -> Array.empty
        | Some projectDirectory ->
            snapshot.Dimensions
            |> Seq.sortBy frameworkOrder
            |> Seq.mapi (fun dimensionOrder dimension ->
                dimension.Items
                |> Seq.choose (fun item ->
                    if not (fileItemTypes.Contains item.ItemType) || isAutoGenerated item then
                        None
                    else
                        item.ResolvedPath
                        |> Option.ofObj
                        |> Option.bind (fun resolved ->
                            let path = Path.GetFullPath resolved.Value

                            if
                                not (isSameOrDescendant projectDirectory path)
                                || isGenerated projectDirectory snapshot path
                            then
                                None
                            else
                                let relative = Path.GetRelativePath(projectDirectory, path)

                                Some
                                    { ItemType = item.ItemType
                                      RelativePath = relative.Replace('\\', '/')
                                      CanonicalRelativePath = canonicalPath insensitive relative
                                      Ordinal = item.Ordinal
                                      DimensionOrder = dimensionOrder })))
            |> Seq.concat
            |> Seq.groupBy (fun file -> file.ItemType, file.CanonicalRelativePath)
            |> Seq.map (fun (_, candidates) ->
                candidates |> Seq.minBy (fun file -> file.DimensionOrder, file.Ordinal))
            |> Seq.sortBy (fun file -> file.DimensionOrder, file.Ordinal)
            |> Seq.toArray

    let private dependencyName (fallback: string) (path: WorkspaceArtifactPath option) =
        match path with
        | None -> fallback
        | Some path ->
            Path.GetFileNameWithoutExtension path.Value
            |> Option.ofObj
            |> Option.filter (String.IsNullOrWhiteSpace >> not)
            |> Option.defaultValue fallback

    let private dependencyCandidates
        insensitive
        (workspace: SolutionWorkspace)
        (project: SolutionProject)
        (snapshot: ProjectEvaluationSnapshot)
        =
        let comparer = pathComparer insensitive

        let projectByPath (path: string) =
            workspace.Contents.Projects
            |> Seq.tryFind (fun candidate ->
                comparer.Equals(candidate.Path.AbsolutePath.Value, path))

        let projectDependency
            (dimension: ProjectEvaluationDimension)
            (reference: EvaluatedReference)
            =
            let resolved = reference.ResolvedPath |> Option.ofObj

            let target =
                resolved
                |> Option.map (fun path -> Path.GetFullPath path.Value)
                |> Option.defaultWith (fun () -> reference.Include.Replace('\\', '/'))

            let identity = $"project:{canonicalPath insensitive target}"

            { Identity = identity
              Name =
                resolved
                |> Option.bind (fun path -> projectByPath path.Value)
                |> Option.map _.Node.Name
                |> Option.defaultWith (fun () -> dependencyName reference.Include resolved)
              CategoryOrder = 0
              Details =
                DependencyDetails.reference
                    DependencyReferenceKind.Project
                    reference.Include
                    resolved
                    dimension }

        let solutionDependencies =
            workspace.Contents.Dependencies
            |> Seq.filter (fun dependency -> dependency.ProjectId = project.Node.Id)
            |> Seq.choose (fun dependency ->
                workspace.Contents.Projects
                |> Seq.tryFind (fun candidate -> candidate.Node.Id = dependency.DependsOnProjectId))
            |> Seq.map (fun target ->
                { Identity = $"project:{canonicalPath insensitive target.Path.AbsolutePath.Value}"
                  Name = target.Node.Name
                  CategoryOrder = 0
                  Details = DependencyDetails.project target.Path.AbsolutePath.Value })

        let evaluated =
            snapshot.Dimensions
            |> Seq.collect (fun dimension ->
                seq {
                    yield! dimension.ProjectReferences |> Seq.map (projectDependency dimension)

                    yield!
                        dimension.Packages
                        |> Seq.map (fun package ->
                            let version =
                                Option.ofObj package.Version |> Option.defaultValue String.Empty

                            { Identity = $"package:{package.Id.ToUpperInvariant()}:{version}"
                              Name =
                                if String.IsNullOrEmpty version then
                                    package.Id
                                else
                                    $"{package.Id} ({version})"
                              CategoryOrder = 1
                              Details = DependencyDetails.package package dimension })

                    yield!
                        dimension.References
                        |> Seq.map (fun reference ->
                            let resolved = reference.ResolvedPath |> Option.ofObj

                            let target =
                                resolved
                                |> Option.map (fun path -> Path.GetFullPath path.Value)
                                |> Option.defaultWith (fun () ->
                                    reference.Include.Replace('\\', '/'))

                            { Identity = $"assembly:{canonicalPath insensitive target}"
                              Name = dependencyName reference.Include resolved
                              CategoryOrder = 2
                              Details =
                                DependencyDetails.reference
                                    DependencyReferenceKind.Assembly
                                    reference.Include
                                    resolved
                                    dimension })

                    yield!
                        dimension.Analyzers
                        |> Seq.map (fun analyzer ->
                            let resolved = analyzer.ResolvedPath |> Option.ofObj

                            let target =
                                resolved
                                |> Option.map (fun path -> Path.GetFullPath path.Value)
                                |> Option.defaultWith (fun () ->
                                    analyzer.Include.Replace('\\', '/'))

                            { Identity = $"analyzer:{canonicalPath insensitive target}"
                              Name = dependencyName analyzer.Include resolved
                              CategoryOrder = 3
                              Details =
                                DependencyDetails.reference
                                    DependencyReferenceKind.Analyzer
                                    analyzer.Include
                                    resolved
                                    dimension })
                })

        Seq.append solutionDependencies evaluated
        |> Seq.groupBy _.Identity
        |> Seq.map (fun (_, candidates) ->
            candidates
            |> Seq.sortBy (fun candidate ->
                -candidate.Details.Length,
                candidate.CategoryOrder,
                candidate.Name,
                candidate.Identity)
            |> Seq.head)
        |> Seq.sortBy (fun candidate -> candidate.CategoryOrder, candidate.Name, candidate.Identity)
        |> Seq.toArray

    let private orderValue dimensionOrder ordinal =
        [ $"{dimensionOrder:D8}"; $"{ordinal:D12}" ]

    let nodes
        insensitive
        (workspace: SolutionWorkspace)
        (project: SolutionProject)
        (snapshot: ProjectEvaluationSnapshot)
        (projectNode: WorkspaceNode)
        =
        let descriptor = workspace.Descriptor
        let placements = ResizeArray<ProjectNodePlacement>()
        let files = semanticFiles insensitive snapshot

        let folderFirstOccurrence =
            Dictionary<string, SemanticFolder>(StringComparer.Ordinal)

        for file in files do
            let segments = file.RelativePath.Split('/', StringSplitOptions.RemoveEmptyEntries)

            for count in 1 .. max 0 (segments.Length - 1) do
                let path = segments[.. count - 1] |> String.concat "/"
                let key = canonicalPath insensitive path
                let occurrence = struct (file.DimensionOrder, file.Ordinal)

                match folderFirstOccurrence.TryGetValue key with
                | true, existing when
                    struct (existing.DimensionOrder, existing.Ordinal) <= occurrence
                    ->
                    ()
                | _ ->
                    folderFirstOccurrence[key] <-
                        { RelativePath = path
                          DimensionOrder = file.DimensionOrder
                          Ordinal = file.Ordinal }

        let folderNodes = Dictionary<string, WorkspaceNode>(StringComparer.Ordinal)

        folderFirstOccurrence
        |> Seq.sortBy (fun (KeyValue(key, folder)) ->
            key.Split('/').Length, folder.DimensionOrder, folder.Ordinal, key)
        |> Seq.iter (fun (KeyValue(key, folder)) ->
            let name = folder.RelativePath.Split('/') |> Array.last

            let node =
                WorkspaceNode.Create(
                    descriptor,
                    WorkspaceNodeKind.ProjectFolder,
                    WorkspaceNodeIdentity.Create
                        $"project-folder:{project.Node.Identity.Value}:{key}",
                    name,
                    snapshot.CapabilityProfile
                )

            folderNodes[key] <- node

            let parentPath =
                folder.RelativePath.Replace('/', Path.DirectorySeparatorChar)
                |> Path.GetDirectoryName
                |> Option.ofObj

            let parentId =
                parentPath
                |> Option.filter (String.IsNullOrEmpty >> not)
                |> Option.map (fun value -> folderNodes[canonicalPath insensitive value].Id)
                |> Option.defaultValue projectNode.Id

            placements.Add
                { PlacementKey = IndexedNodeKey [ "project-folder"; project.Node.Id.Value; key ]
                  PlacementNode = node
                  ParentNodeId = parentId
                  SiblingOrder = "1" :: orderValue folder.DimensionOrder folder.Ordinal @ [ key ] })

        for file in files do
            let parentPath =
                Path.GetDirectoryName(file.RelativePath.Replace('/', Path.DirectorySeparatorChar))
                |> Option.ofObj

            let parentId =
                parentPath
                |> Option.filter (String.IsNullOrEmpty >> not)
                |> Option.map (fun value -> folderNodes[canonicalPath insensitive value].Id)
                |> Option.defaultValue projectNode.Id

            let node =
                WorkspaceNode.Create(
                    descriptor,
                    WorkspaceNodeKind.ProjectFile,
                    WorkspaceNodeIdentity.Create
                        $"project-file:{project.Node.Identity.Value}:{file.ItemType}:{file.CanonicalRelativePath}",
                    Path.GetFileName file.RelativePath
                    |> Option.ofObj
                    |> Option.defaultValue file.RelativePath,
                    snapshot.CapabilityProfile
                )

            placements.Add
                { PlacementKey =
                    IndexedNodeKey
                        [ "project-file"
                          project.Node.Id.Value
                          file.ItemType
                          file.CanonicalRelativePath ]
                  PlacementNode = node
                  ParentNodeId = parentId
                  SiblingOrder =
                    "2" :: orderValue file.DimensionOrder file.Ordinal
                    @ [ file.ItemType; file.CanonicalRelativePath ] }

        let container =
            WorkspaceNode.Create(
                descriptor,
                WorkspaceNodeKind.DependencyContainer,
                WorkspaceNodeIdentity.Create $"dependencies:{project.Node.Identity.Value}",
                "Dependencies",
                WorkspaceCapabilityProfile.ReadOnly
            )

        placements.Add
            { PlacementKey = IndexedNodeKey [ "dependency-container"; project.Node.Id.Value ]
              PlacementNode = container
              ParentNodeId = projectNode.Id
              SiblingOrder = [ "0" ] }

        dependencyCandidates insensitive workspace project snapshot
        |> Seq.iteri (fun index dependency ->
            let node =
                WorkspaceNode.Create(
                    descriptor,
                    WorkspaceNodeKind.Dependency,
                    WorkspaceNodeIdentity.Create
                        $"dependency:{project.Node.Identity.Value}:{dependency.Identity}",
                    dependency.Name,
                    WorkspaceCapabilityProfile.ReadOnly
                )

            placements.Add
                { PlacementKey =
                    IndexedNodeKey [ "dependency"; project.Node.Id.Value; dependency.Identity ]
                  PlacementNode = node
                  ParentNodeId = container.Id
                  SiblingOrder = [ $"{index:D8}"; dependency.Identity ] }

            dependency.Details
            |> Seq.iteri (fun detailIndex detailValue ->
                let detailNode =
                    WorkspaceNode.Create(
                        descriptor,
                        WorkspaceNodeKind.DependencyProperty,
                        WorkspaceNodeIdentity.Create
                            $"dependency:{project.Node.Identity.Value}:{dependency.Identity}:property:{detailValue.DetailId}",
                        $"{detailValue.Label}: {detailValue.Value}",
                        WorkspaceCapabilityProfile.ReadOnly
                    )

                placements.Add
                    { PlacementKey =
                        IndexedNodeKey
                            [ "dependency-property"
                              project.Node.Id.Value
                              dependency.Identity
                              detailValue.DetailId ]
                      PlacementNode = detailNode
                      ParentNodeId = node.Id
                      SiblingOrder = [ $"{detailIndex:D8}"; detailValue.DetailId ] }))

        placements.ToArray()
