<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AnalysisLevel>latest</AnalysisLevel>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Deterministic>true</Deterministic>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>ALSI</Authors>
    </PropertyGroup>
</Project>
