<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="FSharp.Core" Version="10.1.201" />
        <PackageVersion Include="Microsoft.VisualStudio.SolutionPersistence" Version="1.0.52" />
        <PackageVersion Include="MessagePack" Version="3.1.8" />
        <PackageVersion Include="Microsoft.Build" Version="18.7.1" />
        <PackageVersion Include="Microsoft.Build.Locator" Version="1.11.2" />
        <PackageVersion Include="Microsoft.NET.StringTools" Version="18.7.1" />
        <PackageVersion Include="coverlet.collector" Version="10.0.1" />
        <PackageVersion Include="FsUnit.Xunit" Version="7.1.1" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>
</Project>
