<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Eight.cs" Condition="'$(TargetFramework)' == 'net8.0'" />
        <Compile Include="Generated/**/*.cs" />
    </ItemGroup>
</Project>
