<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>Dotnet.CLI.Plus.FakeHost</AssemblyName>
        <RootNamespace>Dotnet.CLI.Plus.FakeHost</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Program.fs" />
    </ItemGroup>
</Project>
