<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>
    <ItemGroup><Compile Include="TransportTests.fs" /></ItemGroup>
    <ItemGroup>
        <None Include="../ConformanceFixtures/Protocol/**/*" Link="ConformanceFixtures/Protocol/%(RecursiveDir)%(Filename)%(Extension)" Pack="false" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
        <PackageReference Include="FsUnit.Xunit" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>
    <ItemGroup><ProjectReference Include="../../src/Dotnet.CLI.Plus.Transport/Dotnet.CLI.Plus.Transport.fsproj" /></ItemGroup>
</Project>
