<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable><AssemblyName>Dotnet.WorkspaceExplorer.Rpc.Benchmarks</AssemblyName><RootNamespace>Dotnet.WorkspaceExplorer.Rpc.Benchmarks</RootNamespace></PropertyGroup><ItemGroup><PackageReference Include="BenchmarkDotNet" /><PackageReference Include="FSharp.Core" /><ProjectReference Include="../../src/Rpc/Dotnet.WorkspaceExplorer.Rpc.fsproj" /></ItemGroup><ItemGroup><Compile Include="WorkspaceRpcSerializationBenchmarks.fs" /><Compile Include="Program.fs" /></ItemGroup></Project>
