<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>Dotnet.CLI.Plus</AssemblyName>
        <RootNamespace>Dotnet.CLI.Plus</RootNamespace>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>dotnet-plus</ToolCommandName>
        <PackageOutputPath>../../build</PackageOutputPath>
        <Description>Additional solution-management commands for the .NET CLI.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Dotnet.CLI.Plus.Core/Dotnet.CLI.Plus.Core.fsproj" />
        <ProjectReference Include="../Dotnet.CLI.Plus.Solution/Dotnet.CLI.Plus.Solution.fsproj" />
        <ProjectReference Include="../Dotnet.CLI.Plus.Transport/Dotnet.CLI.Plus.Transport.fsproj" />
        <ProjectReference Include="../Dotnet.CLI.Plus.MSBuild/Dotnet.CLI.Plus.MSBuild.csproj" />
        <PackageReference Include="FSharp.Core" />
        <PackageReference Include="Microsoft.Build.Locator" IncludeAssets="runtime" />
        <PackageReference Include="Microsoft.NET.StringTools" ExcludeAssets="runtime" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
        <Compile Include="Compatibility.fs" />
        <Compile Include="Pipe.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>
