<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>dotnet-plus</ToolCommandName>
        <PackageOutputPath>../../build</PackageOutputPath>
        <Description>Additional solution-management commands for the .NET CLI.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Dotnet.CLI.Plus.Solution/Dotnet.CLI.Plus.Solution.fsproj" />
        <PackageReference Include="Microsoft.VisualStudio.SolutionPersistence" />
        <PackageReference Include="Spectre.Console" />
        <PackageReference Include="Spectre.Console.Cli" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>
