<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <AssemblyName>Dotnet.CLI.Plus.SystemCapacity</AssemblyName>
        <RootNamespace>Dotnet.CLI.Plus.SystemCapacity</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
        <ProjectReference Include="../../src/Dotnet.CLI.Plus.Transport/Dotnet.CLI.Plus.Transport.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Program.fs" />
    </ItemGroup>
</Project>
