<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Dotnet.CLI.Plus.Solution</AssemblyName>
        <RootNamespace>Dotnet.CLI.Plus.Solution</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Dotnet.CLI.Plus.Core/Dotnet.CLI.Plus.Core.fsproj" />
        <PackageReference Include="Microsoft.VisualStudio.SolutionPersistence" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
        <Compile Include="Projections.fs" />
        <Compile Include="SolutionStore.fs" />
        <Compile Include="LaunchProfiles.fs" />
        <Compile Include="SolutionMutations.fs" />
    </ItemGroup>
</Project>
