<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Dotnet.WorkspaceExplorer.Testing.ScriptedDotnet</AssemblyName><RootNamespace>Dotnet.WorkspaceExplorer.Testing.ScriptedDotnet</RootNamespace><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><PackageReference Include="FSharp.Core" /></ItemGroup><ItemGroup><Compile Include="InvocationSettings.fs" /><Compile Include="ProjectFileEditing.fs" /><Compile Include="TemplateCreation.fs" /><Compile Include="ScriptedDotnetCommand.fs" /><Compile Include="Program.fs" /></ItemGroup></Project>
