<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Dotnet.CLI.Plus.MSBuild</AssemblyName>
        <RootNamespace>Dotnet.CLI.Plus.MSBuild</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Dotnet.CLI.Plus.Core/Dotnet.CLI.Plus.Core.fsproj" />
        <ProjectReference Include="../Dotnet.CLI.Plus.Transport/Dotnet.CLI.Plus.Transport.fsproj" />
        <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Build.Locator" />
        <PackageReference
            Include="Microsoft.NET.StringTools"
            ExcludeAssets="runtime"
            PrivateAssets="all"
        />
    </ItemGroup>
</Project>
